project:
  type: website
  output-dir: docs

website:
  title: "reprodev"
  navbar:
    left:
      - href: index.qmd
        text: About
      - schedule.qmd
      - lectures.qmd
      - tutorial_1.qmd
      - tutorial_1_cloud.qmd
      - tutorial_2.qmd
      - tutorial_2_cloud.qmd
      - tutorial_3.qmd
      - final.qmd
  repo-url: https://github.com/gerkovink/reprodev
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

